### ISSUE TITLE
Discuss branch design and maintenance

### ISSUE THREAD

**Issue by Vathasav** [coderefinery/DEPRECATED-git-archaeology#3]
Consider giving the branch design lesson. Perhaps we can merge git arch and git branch design to give it more visibility, allow for optional modules in it.

**Comment by wikfeldt** [comment]
git branch-design is a great lesson, but far too time-consuming for most workshops (including Lund). And merging the two to increase the visibility of the branch-design lesson is not straightforward since the topics are rather distinct. In any case I can't see any great way to do it...

**Comment by bast** [comment]
I would not combine them but keep them as two modules. It's two different topics.

**Comment by wikfeldt** [comment]
we also probably want to keep the lessons as modular as possible. The other way to highlight the branch-design lesson without actually teaching it (for time reasons) is simply to bring it up

**Comment by bast** [comment]
The thing that I would consider doing is inside this lesson separate the "must read, must understand, must do" from "advanced, nice to do, eventually" then we only teach the "must" and refer to the "can".

**Comment by wikfeldt** [comment]
the branch design lesson is referenced in c0f98c0
Can we close the issue?

**Comment by bast** [comment]
I agree - closing.
